import '../styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by RadBlow.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head> 
        <link rel="icon" href="/favicon.ico" />
        </head>
      <body>
        {children}
        </body>
    </html>
  )
}
